--Print Customers by Doctor Name

SELECT
   MEDI_STORE.DOCTOR.NAME DOCTOR,
   GROUP_CONCAT(MEDI_STORE.CUSTOMER.NAME) PATIENTS 
FROM
   MEDI_STORE.CUSTOMER 
   INNER JOIN
      MEDI_STORE.PRESCRIPTION 
      ON MEDI_STORE.PRESCRIPTION.CUSTOMER_ID = MEDI_STORE.CUSTOMER.ID 
   INNER JOIN
      MEDI_STORE.DOCTOR 
      ON MEDI_STORE.PRESCRIPTION.DOCTOR_ID = MEDI_STORE.DOCTOR.ID 
GROUP BY
   MEDI_STORE.DOCTOR.NAME 
ORDER BY
   MEDI_STORE.DOCTOR.NAME;
   
========================================================

--Print Count of Customer by Each Doctor Name

SELECT
   MEDI_STORE.DOCTOR.NAME DOCTOR,
   COUNT(MEDI_STORE.CUSTOMER.NAME) NUMBER_OF_PATIENTS 
FROM
   MEDI_STORE.CUSTOMER 
   INNER JOIN
      MEDI_STORE.PRESCRIPTION 
      ON MEDI_STORE.PRESCRIPTION.CUSTOMER_ID = MEDI_STORE.CUSTOMER.ID 
   INNER JOIN
      MEDI_STORE.DOCTOR 
      ON MEDI_STORE.PRESCRIPTION.DOCTOR_ID = MEDI_STORE.DOCTOR.ID 
GROUP BY
   MEDI_STORE.DOCTOR.NAME 
ORDER BY
   MEDI_STORE.DOCTOR.NAME;
   
========================================================

--Print Prescription Details by Each Doctor Name

SELECT
   MEDI_STORE.DOCTOR.NAME DOCTOR,
   COUNT(MEDI_STORE.PRESCRIPTION.ID) NUMBER_OF_PRESCRIPTIONS
FROM
   MEDI_STORE.PRESCRIPTION 
   INNER JOIN
      MEDI_STORE.DOCTOR 
      ON MEDI_STORE.PRESCRIPTION.DOCTOR_ID = MEDI_STORE.DOCTOR.ID 
GROUP BY
   MEDI_STORE.DOCTOR.NAME;
   
========================================================

--Print List of Medicines Per Customer Name

SELECT
   MEDI_STORE.CUSTOMER.NAME PATIENT,
   GROUP_CONCAT(MEDI_STORE.MEDICINE.NAME) MEDICINES 
FROM
   MEDI_STORE.PRESCRIPTION 
   INNER JOIN
      MEDI_STORE.PRESCRIPTION_MEDICINE_MAPPING 
      ON MEDI_STORE.PRESCRIPTION.ID = MEDI_STORE.PRESCRIPTION_MEDICINE_MAPPING.PRESCRIPTION_ID 
   INNER JOIN
      MEDI_STORE.CUSTOMER 
      ON MEDI_STORE.CUSTOMER.ID = MEDI_STORE.PRESCRIPTION.CUSTOMER_ID 
   INNER JOIN
      MEDI_STORE.MEDICINE 
      ON MEDI_STORE.PRESCRIPTION_MEDICINE_MAPPING.MEDICINE_ID = MEDI_STORE.MEDICINE.ID 
GROUP BY
   MEDI_STORE.CUSTOMER.NAME 
ORDER BY
   MEDI_STORE.CUSTOMER.NAME;
   
=========================================================

--Print Receivables between 2 Dates

SELECT
   AMOUNT_PAID AMOUNT_PAID_BY_CUSTOMER,
   DATE 
FROM
   MEDI_STORE.BILL 
WHERE
   DATE BETWEEN '2022-01-01' AND '2022-12-31';
   
=========================================================

--Print List of Medicines Ordered between 2 Dates

SELECT
   DATE ORDER_DATE,
   MEDI_STORE.MEDICINE.NAME MEDICINE_ORDERED,
   MEDI_STORE.ORDER.STATUS STATUS
FROM
   MEDI_STORE.ORDER 
   INNER JOIN
      MEDI_STORE.MEDICINE 
      ON MEDI_STORE.MEDICINE.ID = MEDI_STORE.ORDER.MEDICINE_ID 
WHERE
   DATE BETWEEN '2020-01-01' AND '2022-12-31';
   
==========================================================

--Print Count of Order placed for each medicine between 2 Dates

SELECT
   MEDI_STORE.MEDICINE.NAME MEDICINE_ORDERED,
   COUNT(MEDI_STORE.ORDER.ID) NUMBER_OF_ORDERS
FROM
   MEDI_STORE.ORDER 
   INNER JOIN
      MEDI_STORE.MEDICINE 
      ON MEDI_STORE.MEDICINE.ID = MEDI_STORE.ORDER.MEDICINE_ID 
WHERE
   DATE BETWEEN '2020-01-01' AND '2022-12-31' 
GROUP BY
   MEDI_STORE.MEDICINE.NAME;